version: '3'

services:
  terminal:
    container_name: terminal
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - 3000:3000
    networks:
      - proxy-network

networks:
  proxy-network:
    name: proxy-network
    external: true
